language: go

go:
  - 1.8.x
  - 1.9.x

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - go vet $(go list ./... | grep -vF /vendor/)
  - go build ./vendor/github.com/golang/lint/golint
  - ./golint -set_exit_status $(go list ./... | grep -vF /vendor/)
