language: go

go:
  - 1.11.x

install:
  - env GO111MODULE=on go mod download
  - env GO111MODULE=on go mod vendor
  - go get -u github.com/golang/lint/golint

script:
  - go vet $(go list ./... | grep -vF /vendor/)
  - golint -set_exit_status $(go list ./... | grep -vF /vendor/)
