required = ["github.com/golang/lint/golint"]

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/jroimartin/gocui"

[[constraint]]
  branch = "master"
  name = "github.com/y-yagi/configure"

[[constraint]]
  branch = "master"
  name = "github.com/y-yagi/goext"
